PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lwt: <https://litetaryworktopics.com/litetaryworktopics2025#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?book a lwt:OperaLetteraria ;
        dc:title ?title ;
        lwt:èScrittoDa ?author ;
        lwt:haEditore ?publisher ;
        lwt:haDataPubblicazione ?publicationDate ;
        lwt:HaEdizione ?isbn ;
        lwt:HaEdizione ?isbn13 ;
        lwt:HaLingua ?language ;
        lwt:HaGenereLetterario ?genres ;
        lwt:haPagine ?pageCount ;
        lwt:parteDiAntologia ?awards ;
        lwt:HaProvenienzaAutore ?translator ;
        lwt:HaProvenienzaAutore ?places ;
        rdfs:seeAlso ?webURL ;
        lwt:pubblica ?rating .
}
WHERE {
  SERVICE <x-sparql-anything:csv.headers=true,location=Beowulf.csv> {
    [] xyz:id ?id ;
       xyz:Title ?title ;
       xyz:Author ?author ;
       xyz:Translator ?translator ;
       xyz:Publisher ?publisher ;
       xyz:PublicationDate ?publicationDate ;
       xyz:ISBN ?isbn ;
       xyz:ISBN13 ?isbn13 ;
       xyz:Language ?language ;
       xyz:Genres ?genres ;
       xyz:PageCount ?pageCount ;
       xyz:Awards ?awards ;
       xyz:Characters ?characters ;
       xyz:Places ?places ;
       xyz:Rating ?rating ;
       xyz:WebURL ?webURL .
  }

  # Generate unique IRIs for the book, author, and related entities
  BIND(IRI(CONCAT("http://example.org/book/", ?id)) AS ?book)
  BIND(IRI(CONCAT("http://example.org/author/", ?author)) AS ?authorIRI)
  BIND(IRI(CONCAT("http://example.org/publisher/", ?publisher)) AS ?publisherIRI)
  BIND(IRI(CONCAT("http://example.org/translator/", ?translator)) AS ?translatorIRI)
  BIND(IRI(CONCAT("http://example.org/place/", ?places)) AS ?placesIRI)
}
