PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX lwt: <https://litetaryworktopics.com/litetaryworktopics2025#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?opera a lwt:OperaLetteraria ;
        dc:title ?title ;
        lwt:èScrittoDa ?author ;
        lwt:haEditore ?publisherIRI ;
        lwt:haDataPubblicazione ?publicationDate ;
        lwt:HaEdizione ?isbn ;
        lwt:HaLingua ?language ;
        lwt:HaGenereLetterario ?genres ;
        lwt:haPagine ?pageCount ;
        lwt:parteDiAntologia ?awards ;
        lwt:HaProvenienzaAutore ?translator ;
        lwt:HaProvenienzaAutore ?places ;
        rdfs:seeAlso ?webURL ;
        lwt:pubblica ?rating .

  ?publisherIRI a lwt:CasaEditrice ;
                lwt:haNome ?publisher .

}
WHERE {
  SERVICE <x-sparql-anything:csv.headers=true,location=example.json> {
    [] xyz:ID ?id ;
       xyz:Title ?title ;
       xyz:Author ?author ;
       xyz:Publisher ?publisher ;
       xyz:PublicationDate ?publicationDate ;
       xyz:ISBN ?isbn ;
       xyz:Language ?language ;
       xyz:Genres ?genres ;
       xyz:PageCount ?pageCount ;
       xyz:Awards ?awards ;
       xyz:Translator ?translator ;
       xyz:Places ?places ;
       xyz:WebURL ?webURL ;
       xyz:Rating ?rating .
  }

  # Generate unique IRIs aligned with the lwt namespace
  BIND(IRI(CONCAT("https://litetaryworktopics.com/litetaryworktopics2025#", "opera_", ?id)) AS ?opera)
  
  # Generate a unique IRI for the publisher by hashing the publisher name
  BIND(IRI(CONCAT("https://litetaryworktopics.com/litetaryworktopics2025#", "casaEditrice_", MD5(?publisher))) AS ?publisherIRI)

  # Generate a unique IRI for the translator by hashing the translator name
  BIND(IRI(CONCAT("https://litetaryworktopics.com/litetaryworktopics2025#", "translator_", MD5(?translator))) AS ?translatorIRI)
}
